// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhbzFT4XWYvwXaXESbwD5DeaGa6nCOFw',
    appId: '1:968876946947:web:c118c2f2f8d2549cfd4036',
    messagingSenderId: '968876946947',
    projectId: 'project1-c5575',
    authDomain: 'project1-c5575.firebaseapp.com',
    storageBucket: 'project1-c5575.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1j9iJa1_xNOpSAqgeytHc-I55pN5BObE',
    appId: '1:968876946947:android:74ffd8a28d6e1d37fd4036',
    messagingSenderId: '968876946947',
    projectId: 'project1-c5575',
    storageBucket: 'project1-c5575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-XVBZ4Ru9mKbU0KKj9UthpCFPMqxFYM',
    appId: '1:968876946947:ios:0201d3503f49af09fd4036',
    messagingSenderId: '968876946947',
    projectId: 'project1-c5575',
    storageBucket: 'project1-c5575.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-XVBZ4Ru9mKbU0KKj9UthpCFPMqxFYM',
    appId: '1:968876946947:ios:0201d3503f49af09fd4036',
    messagingSenderId: '968876946947',
    projectId: 'project1-c5575',
    storageBucket: 'project1-c5575.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
